### PR TITLE
Savita

### PR DESCRIPTION
**Pull request by SavitaBhor**
Please have look and merge into master

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
What is the difference between the Home and Todos pages? Neither seems to display any Todos.

Also, when I add a todo using the input box, clicking the Add button clears the input, but does not appear to add anything to the database.

**Comment by SavitaBhor** [comment]
> What is the difference between the Home and Todos pages? Neither seems to display any Todos.
> 
> Also, when I add a todo using the input box, clicking the Add button clears the input, but does not appear to add anything to the database.

Home page has search option....when Jacob is done with his code,that will appear there
Todos - shows list of all todos with adding todo option.
All functionality is working fine at my end.Maybe connection error.

**Comment by vdG79uvXn2gjWagYpdCE** [comment]
> > What is the difference between the Home and Todos pages? Neither seems to display any Todos.
> > Also, when I add a todo using the input box, clicking the Add button clears the input, but does not appear to add anything to the database.
> 
> Home page has search option....when Jacob is done with his code,that will appear there
But you indicate that the search is working. Should it not say something like search will go here in the future?

> Todos - shows list of all todos with adding todo option.
> All functionality is working fine at my end.Maybe connection error.
Your endpoint is not responding. If there is a connection error, there needs to be some indication of that.

**Comment by SavitaBhor** [comment]
> > > What is the difference between the Home and Todos pages? Neither seems to display any Todos.
> > > Also, when I add a todo using the input box, clicking the Add button clears the input, but does not appear to add anything to the database.
> > 
> > 
> > Home page has search option....when Jacob is done with his code,that will appear there
> > But you indicate that the search is working. Should it not say something like search will go here in the future?
> 
> > Todos - shows list of all todos with adding todo option.
> > All functionality is working fine at my end.Maybe connection error.
> > Your endpoint is not responding. If there is a connection error, there needs to be some indication of that.
"search is working" comes by default when you add new component....I didn't touch that page, But it is easy to change. That means todo-search component is attached there.
For connection error - I will try to handle that.

**Review by ghost — APPROVED** [review]

**Pull request merged**
